name: Build and Release

on: workflow_dispatch

jobs:
  build_release:
    runs-on: ubuntu-latest
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: get-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: check version
        run: |
          if [ -z "${{ steps.package-version.outputs.current-version }}" ]; then
            echo "No version found in package.json"
            exit 1
          fi
          echo "package.json version is ${{ steps.package-version.outputs.current-version }}"
          script_version=$(grep '^export const scriptVersion = ' src/main.ts | cut -d"'" -f2)
          echo "script version is $script_version"
          if [ "${{ steps.package-version.outputs.current-version }}" != "$script_version" ]; then
            echo "Version in package.json does not match version in src/main.ts"
            exit 1
          fi
          echo "Version in package.json matches version in src/main.ts"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: 'v${{ steps.package-version.outputs.current-version}}'
          release_name: 'Release v${{ steps.package-version.outputs.current-version}}'
          draft: false
          prerelease: false
      - name: Upload release files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/firebot-mage-youtube-integration.js
          asset_name: firebot-mage-youtube-integration-${{ steps.package-version.outputs.current-version}}.js
          asset_content_type: application/octet-stream
